### ISSUE TITLE
Allow adding custom fields to markdown frontmatter

### ISSUE THREAD

**Issue by Shriram-Balaji** [Mermade/widdershins#348] opened 2020-07-14 05:47 UTC
**Is your feature request related to a problem? Please describe.**
Currently, widdershins allows to generate markdown documents, with frontmatter fields that are predefined. In certain scenarios, it might be useful to allow adding custom frontmatter fields / attributes.

**Describe the solution you'd like**
A solution would involve, adding a new `customFields` option to widdershins, and adding these custom fields to the generated markdown front-matter.

**Describe alternatives you've considered**
I'm not currently aware of other ways of doing this directly with widdershins, would be glad to know if there's any existing way of doing it. 

Alternatives I have tried : Parsing the markdown using libraries like `gray-matter` and then adding custom fields to the frontmatter, and then converting it back to a markdown document, which is slightly inconvenient.

**Comment by MikeRalphson** [comment] 2020-07-14 06:10
Dupe of #306? Will prioritise.

**Comment by MikeRalphson** [comment] 2020-07-14 11:26
Thanks, please subscribe to #306 for updates.

**Closed by MikeRalphson** 2020-07-14 11:26 UTC
