### ISSUE TITLE
Slate not rendering output as expected

### ISSUE THREAD

**Issue by asanger** [Mermade/widdershins#223] opened 2019-03-13 16:50 UTC
**Describe the bug**
Generated output does not seem to render in slate properly (at least for OpenAPI 3). It does render in Shins as expected. For a test, I used the `petstore3.json` included in the Widdershins repo.

* [ x ] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Command-line: `node widdershins defs/petstore3.json -o petstore3.html.md`
2. My input file: https://gist.github.com/asanger/489ec74957605200d1f3e010ba9d4cde
3. Place in Slate root directory
4. Visit http://localhost:4567/petstore3.html

**Expected behavior**
Rendering of the document should not appear to be broken in Slate. It should (for the most part) match exactly how Shins renders.

**Screenshots**
When loading this file with shins, I get valid rendering:
![image](https://user-images.githubusercontent.com/1369779/54297805-ef5c0000-458d-11e9-98ea-921de16164a1.png)

When loading this file with slate (cloned repo, no alterations), I get broken rendering:
![image](https://user-images.githubusercontent.com/1369779/54297766-db180300-458d-11e9-8026-6799c2a105f0.png)

**Versions**:
- Node.js: 11.5.0 
- Slate: 2.3.1

**Comment by MikeRalphson** [comment] 2019-03-17 15:56
Could you let me know what operating system you're running on?

**Comment by asanger** [comment] 2019-03-17 17:56
macOS Mojave 10.14.3

**Comment by mariohartman** [comment] 2019-04-10 22:30
with the version that you can install from npm this does not happens but I can reproduce this with master.

**Comment by MikeRalphson** [comment] 2019-04-11 08:40
@mariohartman thanks that should be helpful in narrowing down the problem.

**Comment by fdanielsen** [comment] 2019-07-09 13:03
I came across this issue while trying to use the current master instead of latest release, since I want the new `--omitHeader` option. When switching to master I got the same problem with untranslated Markdown. Looking at the generated Markdown file I saw that content now is grouped within `<section>` elements.

Slate which is based on Middleman uses Ruby's redcarpet Markdown renderer, which seems to not convert [Markdown within block level HTML elements](https://github.com/vmg/redcarpet/issues/13).

So I think this is the problem here. Removing the `<section>` elements from the generated Markdown restores rendering in Slate. I'm sure you have a reason for updating with this, maybe some more flexibility in styling in Shins templates? Don't know what the best solution would be then to support both.

**Comment by MikeRalphson** [comment] 2019-07-09 14:14
Thanks for the info, that was my guess as to what was causing this issue, but I hadn't had time to test it.

As it is holding up a release, I will modify the templates to use a helper function and make the section tags only output when --respec is set.

**Comment by fdanielsen** [comment] 2019-07-09 14:22
Sounds good. I fixed it for my development right now by overriding the templates, I had wanted to adjust the header levels anyway.

**Comment by MikeRalphson** [comment] 2020-03-28 20:13
Should be fixed in version `4.0.0`, which includes breaking changes (please see the `README.md` file).

**Closed by MikeRalphson** 2020-03-28 20:13 UTC
Labels: regression, slate-compat
