### ISSUE TITLE
During conversion, should ignore comments in YAML files

### ISSUE THREAD

**Issue by bdeanindy** [Mermade/widdershins#40] opened 2017-09-15 03:20 UTC
If there are any hash symbols (pound symbols) used to denote comments in a YAML file, this reads those and the conversion to Markdown is totally broken.

To recreate, just add a comment at the very first line of your YAML and then convert the file to Markdown.

**Comment by MikeRalphson** [comment] 2017-09-15 06:40
Hi @bdeanindy - thanks for reporting this, unfortunately I can't reproduce it using your steps.

By any chance are you using the API convert() function? If so, you need to pass a Javascript object parsed from your YAML file to this function, not a string (in which case the data will be interpreted as API Blueprint).

The other possibility (if you're using the commandline `widdershins.js`) is that there is some formatting error in your YAML file which is causing the parsing to fail. Could you post the failing file as a gist?

I will improve the error logging for the second case.

**Comment by MikeRalphson** [comment] 2017-09-15 06:45
If you're using the command-line, please try again with v2.3.0 - otherwise it may be the README.md documentation which needs clarifying.

**Comment by MikeRalphson** [comment] 2017-09-27 06:53
Closing due to inactivity - but please feel free to reopen the issue if necessary.

**Closed by MikeRalphson** 2017-09-27 06:53 UTC
